import Head from "next/head"
import Button from "../lib/button/Button"
import { useRouter } from "next/router"
import { BiRocket } from "react-icons/bi";
import CenterAll from "../lib/alignment/CenterAll";
import { signIn, useSession } from "next-auth/react";
import { useEffect } from "react";

export default function Home() {
  const router = useRouter();
  const { data: session, status } = useSession();
  
  useEffect(() => {
    if(session){
      router.push("/planner");
    }else{
      router.push("/");
    }
  }, [session])

  return (
    <>
      <Head>
        <title>SCU Course Planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenterAll>
        <h1>SCU Course Planner</h1>
        <Button
          icon={<BiRocket/>}
          color={"red"}
          onClick={signIn}
        >
          Create An Account
        </Button>
      </CenterAll>
    </>
  )
}
